import { create } from 'zustand';
import { persist } from 'zustand/middleware';

const translations = {
  en: {
    // Nav
    dashboard: 'Dashboard',
    rentals: 'Rentals',
    customers: 'Customers',
    fleet: 'Vehicles',
    payments: 'Payments',
    reports: 'Reports',
    settings: 'Settings',
    logout: 'Logout',
    trialActive: 'Trial active',

    // Common
    cancel: 'Cancel',
    save: 'Save',
    confirm: 'Confirm',
    back: 'Back',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    add: 'Add',
    close: 'Close',
    loading: 'Loading...',
    search: 'Search...',
    select: 'Select...',
    action: 'Action',
    yes: 'Yes',
    no: 'No',
    required: 'required',
    somethingWentWrong: 'Something went wrong',

    // Dashboard
    activeRentals: 'Active Rentals',
    overdue: 'Overdue',
    monthRevenue: 'Month Revenue',
    depositHeld: 'Deposit Held',
    todayRentals: "Today's Rentals",
    overdueRentals: 'Overdue Rentals',
    returningSoon: 'Returning Soon',
    quickActions: 'Quick Actions',
    viewAll: 'View all',
    noOverdueRentals: 'No overdue rentals!',
    allRentalsOnTrack: 'All rentals are on track',
    noUpcomingReturns: 'No returns in the next 2 days',
    newRentalBtn: '＋ New Rental',
    addCustomerBtn: '＋ Add Customer',
    addVehicleBtn: '＋ Add Vehicle',
    viewReportsBtn: '📊 View Reports',
    today: 'Today',
    days: 'days',
    daysOverdue: 'overdue',

    // Customers
    addCustomer: 'Add New Customer',
    fullName: 'Full Name',
    phone: 'Phone',
    email: 'Email',
    aadhaarNumber: 'Aadhaar Number',
    dlNumber: 'DL Number',
    city: 'City',
    source: 'Source',
    address: 'Address',
    saveCustomer: 'Save Customer',
    blacklist: 'Blacklist',
    unblock: 'Unblock',
    customerProfile: 'Customer Profile',
    joined: 'Joined',
    amountPaid: 'Amount Paid',
    documents: 'ID Proofs & Documents',
    front: 'Front',
    backSide: 'Back',
    upload: 'Upload',
    replace: 'Replace',
    aadhaarCard: 'Aadhaar Card',
    drivingLicense: 'Driving License',
    passport: 'Passport',
    voterId: 'Voter ID',
    rentalHistory: 'Rental History',
    noCustomers: 'No customers yet',
    noCustomersDesc: 'Add your first customer to get started.',
    blacklistedStatus: '⛔ Blacklisted',
    manualFlagReason: 'Manually flagged',
    blockConfirmTitle: 'Block Customer',
    blockConfirmDesc: 'Block this customer from making new rentals?',
    unblockConfirmTitle: 'Unblock Customer',
    unblockConfirmDesc: 'Allow this customer to rent again?',

    // Fleet/Inventory
    fleetInventory: 'Vehicles Inventory',
    addItem: 'Add Vehicle',
    brand: 'Brand',
    model: 'Model',
    year: 'Year',
    color: 'Color',
    category: 'Category',
    fuelType: 'Fuel Type',
    engineCc: 'Engine CC',
    registrationNumber: 'Registration No.',
    dailyRate: 'Daily Rate',
    depositAmount: 'Deposit',
    lateFeePerDay: 'Late Fee/Day',
    insuranceExpiry: 'Insurance Expiry',
    pucExpiry: 'PUC Expiry',
    photo: 'Vehicle Photo',
    description: 'Description',
    logService: '🔧 Log Service',
    rentOut: '🔑 Rent Out',
    available: 'Available',
    rented: 'Rented',
    maintenance: 'Maintenance',
    inMaintenance: 'In Maintenance',
    docsExpiringSoon: '⚠️ Documents expiring soon',
    noItemsFound: 'No items found',
    noItemsDesc: 'Add your first vehicle or equipment.',
    addToFleet: 'Add Vehicle',
    oilChangePlaceholder: 'Oil change, tyre replacement, etc.',
    servicedBy: 'Serviced By',
    nextServiceDate: 'Next Service Date',
    setStatus: 'Set Status',
    saveLog: 'Save Log',
    keepCurrent: 'Keep current',

    // Rentals
    rentalDetails: 'Rental Details',
    all: 'All',
    returned: 'Returned',
    cancelled: 'Cancelled',
    reserved: 'Reserved',
    extend: 'Extend',
    returnBtn: 'Return ✓',
    processReturn: 'Process Return',
    actualReturnDate: 'Actual Return Date',
    depositToReturn: 'Deposit to Return (₹)',
    penalty: 'Penalty (₹)',
    paymentMethod: 'Payment Method',
    returnNotes: 'Return Notes',
    notes: 'Notes',
    confirmReturn: 'Confirm Return',
    extendRental: 'Extend Rental',
    currentDue: 'Current due',
    newReturnDate: 'New Return Date',
    reasonForExtension: 'Reason for Extension',
    amountPending: 'Pending',
    settled: '✓ Settled',
    recordPayment: '＋ Record Payment',
    printInvoice: '📄 Print Invoice',
    printSlip: '🎟️ Print Slip',
    sendWhatsAppAlert: 'Send WhatsApp Alert',
    financialSummary: 'Financial Summary',
    rentalAmount: 'Rental Amount',
    depositTaken: 'Deposit Taken',
    totalPaid: 'Total Paid',
    depositReturned: 'Deposit Returned',
    extensions: 'Extensions',
    paymentHistory: 'Payment History',
    noRentalsFound: 'No rentals found',
    createFirstRental: 'Create your first rental to get started.',
    createRental: 'Create Rental',
    selectCustomer: 'Select customer...',
    selectExistingCustomer: 'Select Existing Customer',
    createNewCustomer: 'Create New Customer',
    searchVehiclePlaceholder: '🔍 Search vehicle by number, name, brand...',
    selectAvailableItem: 'Select available item...',
    discount: 'Discount (₹)',
    rentalSummary: '📋 Rental Summary',
    duration: 'Duration',
    totalRentalAmount: 'Total Rental Amount',
    depositNotice: '💡 Deposit collected separately via payment',
    dueToday: 'Due today!',
    left: 'left',
    agreement: 'Agreement',

    // Payments
    netRevenue: 'Net Revenue',
    transactions: 'Transactions',
    totalCollected: 'Total Collected',
    totalRefunded: 'Total Refunded',
    paymentTransactions: 'Payment Transactions',
    noPaymentsFound: 'No payments found',

    // Reports
    reportsAnalytics: 'Reports & Analytics',
    performanceOverview: 'Business performance overview',
    exportRentals: '⬇ Export Rentals CSV',
    exportCustomers: '⬇ Export Customers CSV',
    avgRentalValue: 'Avg Rental Value',
    overdueRate: 'Overdue Rate',
    monthlyRevenueRentals: 'Monthly Revenue & Rentals',
    topVehicles: '🏆 Top Performing Vehicles',
    topCustomers: '⭐ Top Customers',
    revenueByCategory: 'Revenue by Category',
    noDataYet: 'No data yet',

    // Settings
    settingsTitle: 'Settings',
    profile: 'Profile',
    notifications: 'Notifications',
    staff: 'Staff',
    plans: 'Plans',
    integrations: 'Integrations',
    agencyProfile: 'Agency Profile',
    agencyName: 'Agency Name',
    ownerName: 'Owner Name',
    alternatePhone: 'Alternate Phone',
    stateLabel: 'State',
    pincode: 'Pincode',
    gstin: 'GSTIN',
    businessType: 'Business Type',
    saveChanges: 'Save Changes',
    notificationSettings: 'Notification Settings',
    whatsappAlerts: 'WhatsApp Alerts',
    whatsappAlertsDesc: 'Send overdue + confirmation messages via WhatsApp',
    whatsappNumber: 'WhatsApp Business Number',
    emailNotifications: 'Email Notifications',
    emailNotificationsDesc: 'Send rental confirmations and overdue alerts via email',
    overdueAlertDays: 'Overdue Alert (days after due date)',
    depositPolicy: 'Deposit Policy (shown in alerts)',
    saveNotificationSettings: 'Save Notification Settings',
    staffMembers: 'Staff Members',
    inviteStaff: '＋ Invite Staff',
    inviteStaffTitle: 'Invite Staff Member',
    inviteStaffDesc: 'An invitation email with temporary password will be sent.',
    owner: 'Owner',
    remove: 'Remove',
    currentPlan: 'Current Plan',
    connected: 'Connected',
    configureInEnv: 'Configure in .env',

    // Onboarding/Auth
    emailAddress: 'Email Address',
    password: 'Password',
    login: 'Login',
    signIn: 'Sign In',
    register: 'Register',
    createAccount: 'Create Account',
    forgotPassword: 'Forgot Password',
    forgotPasswordBtn: 'Forgot Password?',
    resetPassword: 'Reset Password',
    donotHaveAccount: 'Don\'t have an account?',
    alreadyHaveAccount: 'Already have an account?',
    backToLogin: 'Back to Login',
    sendResetLink: 'Send Reset Link',
    selectLanguage: 'Language / భాష',
  },
  te: {
    // Nav
    dashboard: 'డాష్‌బోర్డ్',
    rentals: 'అద్దెలు',
    customers: 'కస్టమర్లు',
    fleet: 'వాహనాలు',
    payments: 'చెల్లింపులు',
    reports: 'రిపోర్టులు',
    settings: 'సెట్టింగ్స్',
    logout: 'లాగౌట్',
    trialActive: 'ఉచిత ట్రయల్ సక్రియంగా ఉంది',

    // Common
    cancel: 'రద్దు చేయి',
    save: 'సేవ్ చేయి',
    confirm: 'ధృవీకరించు',
    back: 'వెనుకకు',
    edit: 'సవరించు',
    delete: 'తొలగించు',
    view: 'చూడు',
    add: 'జోడించు',
    close: 'మూసివేయి',
    loading: 'లోడ్ అవుతోంది...',
    search: 'వెతకండి...',
    select: 'ఎంచుకోండి...',
    action: 'చర్య',
    yes: 'అవును',
    no: 'వద్దు',
    required: 'తప్పనిసరి',
    somethingWentWrong: 'ఏదో తప్పు జరిగింది',

    // Dashboard
    activeRentals: 'యాక్టివ్ అద్దెలు',
    overdue: 'గడువు దాటినవి',
    monthRevenue: 'ఈ నెల ఆదాయం',
    depositHeld: 'డిపాజిట్ నిల్వ',
    todayRentals: 'ఈరోజు అద్దెలు',
    overdueRentals: 'గడువు దాటిన అద్దెలు',
    returningSoon: 'త్వరలో తిరిగి వచ్చేవి',
    quickActions: 'త్వరిత చర్యలు',
    viewAll: 'అన్నీ చూడు',
    noOverdueRentals: 'గడువు దాటిన అద్దెలు ఏవీ లేవు!',
    allRentalsOnTrack: 'అన్ని అద్దెలు సరిగ్గా ఉన్నాయి',
    noUpcomingReturns: 'రాబోయే 2 రోజుల్లో ఎటువంటి తిరుగుదలలు లేవు',
    newRentalBtn: '＋ కొత్త అద్దె',
    addCustomerBtn: '＋ కస్టమర్ ని చేర్చు',
    addVehicleBtn: '＋ వాహనాన్ని చేర్చు',
    viewReportsBtn: '📊 రిపోర్టులు చూడు',
    today: 'ఈరోజు',
    days: 'రోజులు',
    daysOverdue: 'ఆలస్యం',

    // Customers
    addCustomer: 'కొత్త కస్టమర్ ని చేర్చండి',
    fullName: 'పూర్తి పేరు',
    phone: 'ఫోన్ నంబర్',
    email: 'ఈమెయిల్',
    aadhaarNumber: 'ఆధార్ నంబర్',
    dlNumber: 'డ్రైవింగ్ లైసెన్స్ నంబర్',
    city: 'నగరం',
    source: 'కస్టమర్ వచ్చిన మార్గం',
    address: 'చిరునామా',
    saveCustomer: 'కస్టమర్ ను సేవ్ చేయి',
    blacklist: 'బ్లాక్‌లిస్ట్ చేయి',
    unblock: 'అన్‌బ్లాక్ చేయి',
    customerProfile: 'కస్టమర్ ప్రొఫైల్',
    joined: 'చేరిన తేదీ',
    amountPaid: 'చెల్లించిన మొత్తం',
    documents: 'గుర్తింపు పత్రాలు',
    front: 'ముందు భాగం',
    backSide: 'వెనుక భాగం',
    upload: 'అప్‌లోడ్',
    replace: 'మార్చండి',
    aadhaarCard: 'ఆధార్ కార్డ్',
    drivingLicense: 'డ్రైవింగ్ లైసెన్స్',
    passport: 'పాస్‌పోర్ట్',
    voterId: 'ఓటర్ ఐడి',
    rentalHistory: 'అద్దె చరిత్ర',
    noCustomers: 'కస్టమర్లు ఇంకా లేరు',
    noCustomersDesc: 'ప్రారంభించడానికి మీ మొదటి కస్టమర్‌ను జోడించండి.',
    blacklistedStatus: '⛔ బ్లాక్‌లిస్ట్ చేయబడింది',
    manualFlagReason: 'మాన్యువల్‌గా ఫ్లాగ్ చేయబడింది',
    blockConfirmTitle: 'కస్టమర్‌ను బ్లాక్ చేయండి',
    blockConfirmDesc: 'ఈ కస్టమర్‌ను కొత్త అద్దెలు తీసుకోకుండా బ్లాక్ చేయాలా?',
    unblockConfirmTitle: 'కస్టమర్‌ను అన్‌బ్లాక్ చేయండి',
    unblockConfirmDesc: 'ఈ కస్టమర్‌ను మళ్లీ అద్దెకు తీసుకోవడానికి అనుమతించాలా?',

    // Fleet/Inventory
    fleetInventory: 'వాహనాల జాబితా',
    addItem: 'కొత్త వాహనాన్ని చేర్చండి',
    brand: 'బ్రాండ్',
    model: 'మోడల్',
    year: 'సంవత్సరం',
    color: 'రంగు',
    category: 'వర్గం',
    fuelType: 'ఇంధనం రకం',
    engineCc: 'ఇంజిన్ CC',
    registrationNumber: 'రిజిస్ట్రేషన్ నంబర్',
    dailyRate: 'రోజువారీ ధర',
    depositAmount: 'డిపాజిట్',
    lateFeePerDay: 'ఆలస్య రుసుము/రోజు',
    insuranceExpiry: 'భీమా గడువు తేదీ',
    pucExpiry: 'PUC గడువు తేదీ',
    photo: 'వాహనం ఫోటో',
    description: 'వివరణ',
    logService: '🔧 సర్వీస్ నమోదు',
    rentOut: '🔑 అద్దెకు ఇవ్వండి',
    available: 'అందుబాటులో ఉంది',
    rented: 'అద్దెకు ఇవ్వబడింది',
    maintenance: 'సర్వీసింగ్ లో ఉంది',
    inMaintenance: 'సర్వీసింగ్ లో ఉంది',
    docsExpiringSoon: '⚠️ పత్రాల గడువు త్వరలో ముగుస్తుంది',
    noItemsFound: 'ఏ వాహనాలు కనుగొనబడలేదు',
    noItemsDesc: 'వాహనాల జాబితాకు మీ మొదటి వాహనాన్ని జోడించండి.',
    addToFleet: 'జాబితాలో చేర్చు',
    oilChangePlaceholder: 'ఆయిల్ మార్పు, టైర్ మార్పిడి మొదలైనవి.',
    servicedBy: 'సర్వీస్ చేసిన వారు',
    nextServiceDate: 'తదుపరి సర్వీస్ తేదీ',
    setStatus: 'స్థితిని సెట్ చేయి',
    saveLog: 'లాగ్ సేవ్ చేయి',
    keepCurrent: 'ప్రస్తుత స్థితిలోనే ఉంచు',

    // Rentals
    rentalDetails: 'అద్దె వివరాలు',
    all: 'అన్నీ',
    returned: 'తిరిగి వచ్చింది',
    cancelled: 'రద్దయింది',
    reserved: 'రిజర్వ్ చేయబడింది',
    extend: 'పొడిగించు',
    returnBtn: 'తిరిగి వచ్చింది ✓',
    processReturn: 'తిరుగు ప్రయాణం నమోదు',
    actualReturnDate: 'తిరిగి వచ్చిన తేదీ',
    depositToReturn: 'తిరిగి ఇవ్వాల్సిన డిపాజిట్ (₹)',
    penalty: 'పెనాల్టీ (₹)',
    paymentMethod: 'చెల్లింపు పద్ధతి',
    returnNotes: 'తిరిగి వచ్చినప్పటి నోట్స్',
    notes: 'గమనికలు',
    confirmReturn: 'తిరుగుదలను ధృవీకరించు',
    extendRental: 'అద్దె పొడిగింపు',
    currentDue: 'ప్రస్తుత గడువు',
    newReturnDate: 'కొత్త తిరుగు ప్రయాణ తేదీ',
    reasonForExtension: 'పొడిగింపు కారణం',
    amountPending: 'బాకీ మొత్తం',
    settled: '✓ క్లియర్ అయింది',
    recordPayment: '＋ చెల్లింపు నమోదు',
    printInvoice: '📄 ఇన్వాయిస్ ప్రింట్',
    printSlip: '🎟️ స్లిప్ ప్రింట్',
    sendWhatsAppAlert: 'వాట్సాప్ అలర్ట్ పంపండి',
    financialSummary: 'ఆర్థిక సారాంశం',
    rentalAmount: 'అద్దె మొత్తం',
    depositTaken: 'తీసుకున్న డిపాజిట్',
    totalPaid: 'మొత్తం చెల్లించింది',
    depositReturned: 'డిపాజిట్ తిరిగి ఇచ్చింది',
    extensions: 'పొడిగింపులు',
    paymentHistory: 'చెల్లింపుల చరిత్ర',
    noRentalsFound: 'అద్దెలు ఏవీ కనుగొనబడలేదు',
    createFirstRental: 'ప్రారంభించడానికి మీ మొదటి అద్దెను సృష్టించండి.',
    createRental: 'అద్దెను సృష్టించండి',
    selectCustomer: 'కస్టమర్ ను ఎంచుకోండి...',
    selectExistingCustomer: 'ఉన్న కస్టమర్ ను ఎంచుకోండి',
    createNewCustomer: 'కొత్త కస్టమర్ ను సృష్టించండి',
    searchVehiclePlaceholder: '🔍 వాహనం నంబర్, పేరు లేదా బ్రాండ్ తో వెతకండి...',
    selectAvailableItem: 'అందుబాటులో ఉన్న వాహనాన్ని ఎంచుకోండి...',
    discount: 'డిస్కౌంట్ (₹)',
    rentalSummary: '📋 అద్దె సారాంశం',
    duration: 'సమయం',
    totalRentalAmount: 'మొత్తం అద్దె ధర',
    depositNotice: '💡 డిపాజిట్ చెల్లింపు ద్వారా విడిగా సేకరించబడుతుంది',
    dueToday: 'ఈరోజే గడువు!',
    left: 'రోజులు మిగిలి ఉన్నాయి',
    agreement: 'ఒప్పందం',

    // Payments
    netRevenue: 'నికర రాబడి',
    transactions: 'లావాదేవీలు',
    totalCollected: 'మొత్తం వసూలు చేసింది',
    totalRefunded: 'మొత్తం రీఫండ్ చేసింది',
    paymentTransactions: 'చెల్లింపుల లావాదేవీలు',
    noPaymentsFound: 'చెల్లింపులు ఏవీ కనుగొనబడలేదు',

    // Reports
    reportsAnalytics: 'రిపోర్టులు & విశ్లేషణలు',
    performanceOverview: 'వ్యాపార పనితీరు అవలోకనం',
    exportRentals: '⬇ అద్దెలు CSV ఎగుమతి',
    exportCustomers: '⬇ కస్టమర్లు CSV ఎగుమతి',
    avgRentalValue: 'సగటు అద్దె విలువ',
    overdueRate: 'ఆలస్య రేటు',
    monthlyRevenueRentals: 'నెలవారీ ఆదాయం & అద్దెలు',
    topVehicles: '🏆 అత్యధిక ఆదాయం తెచ్చిన వాహనాలు',
    topCustomers: '⭐ అగ్ర కస్టమర్లు',
    revenueByCategory: 'వర్గాల వారీగా ఆదాయం',
    noDataYet: 'ఇంకా డేటా లేదు',

    // Settings
    settingsTitle: 'సెట్టింగ్స్',
    profile: 'ప్రొఫైల్',
    notifications: 'నోటిఫికేషన్లు',
    staff: 'సిబ్బంది',
    plans: 'ప్లాన్లు',
    integrations: 'ఇంటిగ్రేషన్స్',
    agencyProfile: 'ఏజెన్సీ ప్రొఫైల్',
    agencyName: 'ఏజెన్సీ పేరు',
    ownerName: 'యజమాని పేరు',
    alternatePhone: 'ప్రత్యామ్నాయ ఫోన్',
    stateLabel: 'రాష్ట్రం',
    pincode: 'పిన్‌కోడ్',
    gstin: 'GSTIN',
    businessType: 'వ్యాపార రకం',
    saveChanges: 'మార్పులను సేవ్ చేయి',
    notificationSettings: 'నోటిఫికేషన్ సెట్టింగ్స్',
    whatsappAlerts: 'వాట్సాప్ అలర్ట్‌లు',
    whatsappAlertsDesc: 'వాట్సాప్ ద్వారా గడువు ముగిసిన మరియు నిర్ధారణ సందేశాలను పంపండి',
    whatsappNumber: 'వాట్సాప్ బిజినెస్ నంబర్',
    emailNotifications: 'ఈమెయిల్ నోటిఫికేషన్లు',
    emailNotificationsDesc: 'ఈమెయిల్ ద్వారా అద్దె నిర్ధారణలు మరియు గడువు అలర్ట్‌లను పంపండి',
    overdueAlertDays: 'గడువు ముగిసిన అలర్ట్ (గడువు తేదీ తర్వాత రోజులు)',
    depositPolicy: 'డిపాజిట్ విధానం (అలర్ట్‌లలో చూపబడుతుంది)',
    saveNotificationSettings: 'నోటిఫికేషన్ సెట్టింగ్స్ సేవ్ చేయి',
    staffMembers: 'సిబ్బంది సభ్యులు',
    inviteStaff: '＋ సిబ్బందిని ఆహ్వానించండి',
    inviteStaffTitle: 'సిబ్బంది సభ్యుడిని ఆహ్వానించండి',
    inviteStaffDesc: 'తాత్కాలిక పాస్‌వర్డ్‌తో ఆహ్వాన ఈమెయిల్ పంపబడుతుంది.',
    owner: 'యజమాని',
    remove: 'తొలగించు',
    currentPlan: 'ప్రస్తుత ప్లాన్',
    connected: 'కనెక్ట్ చేయబడింది',
    configureInEnv: '.env లో కాన్ఫిగర్ చేయండి',

    // Onboarding/Auth
    emailAddress: 'ఈమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    login: 'లాగిన్',
    signIn: 'లాగిన్ అవ్వండి',
    register: 'నమోదు చేసుకోండి',
    createAccount: 'ఖాతాను సృష్టించండి',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా',
    forgotPasswordBtn: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    resetPassword: 'పాస్‌వర్డ్ రీసెట్ చేయి',
    donotHaveAccount: 'ఖాతా లేదా?',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    backToLogin: 'లాగిన్ పేజీకి తిరిగి వెళ్ళండి',
    sendResetLink: 'రీసెట్ లింక్ పంపండి',
    selectLanguage: 'భాష / Language',
  }
};

// Prefilled WhatsApp message templates generator
export const getWhatsAppLink = (phone, type, data, lang = 'en') => {
  const formattedPhone = phone.replace(/[^0-9]/g, '');
  const cleanPhone = formattedPhone.startsWith('91') && formattedPhone.length === 12
    ? formattedPhone 
    : formattedPhone.length === 10 
      ? `91${formattedPhone}` 
      : formattedPhone;

  let text = '';
  if (lang === 'te') {
    if (type === 'confirmation') {
      text = `నమస్తే ${data.customerName}, మీ ${data.vehicleName} (${data.regNo || 'N/A'}) అద్దె ${data.startDate} నుండి ${data.returnDate} వరకు విజయవంతంగా ఖరారైంది.\n\nమొత్తం అద్దె: ₹${data.amount}\nడిపాజిట్: ₹${data.deposit}\nఅద్దె నంబర్: ${data.rentalNumber}.\n\nధన్యవాదాలు!`;
    } else if (type === 'reminder') {
      text = `నమస్తే ${data.customerName}, మీ ${data.vehicleName} అద్దె గడువు రేపు (${data.dueDate}) తో ముగుస్తుంది. దయచేసి అదనపు ఆలస్య రుసుము పడకుండా సమయానికి వాహనాన్ని తిరిగి ఇవ్వండి. ధన్యవాదాలు!`;
    } else if (type === 'overdue') {
      text = `అలర్ట్: నమస్తే ${data.customerName}, మీ ${data.vehicleName} (${data.regNo || 'N/A'}) అద్దె గడువు ${data.dueDate} నాటితో ముగిసింది. ఇది ఇప్పటికి ${data.days} రోజులు ఆలస్యమైంది.\n\nదయచేసి వెంటనే వాహనాన్ని తిరిగి ఇవ్వండి లేదా మమ్మల్ని సంప్రదించండి. ఆలస్య రుసుము వర్తిస్తుంది.\nధన్యవాదాలు, ${data.agencyName}`;
    } else if (type === 'return') {
      text = `నమస్తే ${data.customerName}, మీ ${data.vehicleName} అద్దె విజయవంతంగా తిరిగి ఇవ్వబడింది. చెల్లించిన మొత్తం: ₹${data.amount}, రీఫండ్ చేసిన డిపాజిట్: ₹${data.depositReturned}.\n\nధన్యవాదాలు, మళ్ళీ రండి!`;
    } else {
      text = `నమస్తే ${data.customerName}, మిమ్మల్ని సంప్రదించడానికి మెసేజ్ పంపాము.`;
    }
  } else {
    // English (default)
    if (type === 'confirmation') {
      text = `Hi ${data.customerName}, your rental of ${data.vehicleName} (${data.regNo || 'N/A'}) is confirmed from ${data.startDate} to ${data.returnDate}.\n\nTotal Rent: ₹${data.amount}\nSecurity Deposit: ₹${data.deposit}\nRental No: ${data.rentalNumber}.\n\nThank you!`;
    } else if (type === 'reminder') {
      text = `Hi ${data.customerName}, your rental of ${data.vehicleName} is due for return tomorrow, ${data.dueDate}. Please return on time to avoid late fees. Thank you!`;
    } else if (type === 'overdue') {
      text = `ALERT: Hi ${data.customerName}, your rental of ${data.vehicleName} (${data.regNo || 'N/A'}) was due on ${data.dueDate} and is now ${data.days} days overdue.\n\nPlease return the vehicle immediately or contact us. Additional charges apply.\nThanks, ${data.agencyName}`;
    } else if (type === 'return') {
      text = `Hi ${data.customerName}, your rental of ${data.vehicleName} has been returned successfully. Total Paid: ₹${data.amount}, Deposit Refunded: ₹${data.depositReturned}.\n\nThank you for renting with us!`;
    } else {
      text = `Hi ${data.customerName}, reaching out regarding your rental.`;
    }
  }

  return `https://wa.me/${cleanPhone}?text=${encodeURIComponent(text)}`;
};

const useLangStore = create(
  persist(
    (set, get) => ({
      language: 'en',
      setLanguage: (lang) => set({ language: lang }),
      t: (key) => {
        const lang = get().language;
        return translations[lang]?.[key] || translations['en']?.[key] || key;
      }
    }),
    {
      name: 'rentflow-lang',
    }
  )
);

export default useLangStore;
